### ISSUE TITLE
React Snippets not Loading

### ISSUE THREAD

**Issue by SmashMineGame** [rafamadriz/friendly-snippets#100]
The snippets for react-js aren't loading but the normal javascript snippets are.  The filetype of my react files are "javascript.jsx" if that helps. Is there a way I can fix this?

**Comment by rafamadriz** [comment]
If I open a `test.jsx` file, I get react snippets. Can you provide a minimal config to reproduce ?

**Comment by pelachile** [comment]
How do I get the react snippets to load in .js files? They work fine in .jsx files and thank you for this plugin.

**Comment by OkelleyDevelopment** [comment]
@pelachile 
Note my config is setup for nvim v0.7.0  and use `nvim-cmp` with `luasnip`

I was able to get the react snippets in base `.js` files by adding the following line in my config
![image](https://user-images.githubusercontent.com/56930510/168412122-42d5d0dd-9274-428b-b9b0-de3891431aed.png)

**Comment by OkelleyDevelopment** [comment]
If this issue still persists feel free to reopen the issue and we will revisit it, but for now I am closing the issue :smile:
