### ISSUE TITLE
Extend typescript snippets due to #88 changes

### ISSUE THREAD

**Issue by timsofteng** [rafamadriz/friendly-snippets#105]
Hello. I've notices you drop mixing sources for some complex filetypes (ts and tsx in my case).
https://github.com/rafamadriz/friendly-snippets/issues/88

So now I should invoke additional command to mix js and ts snippets. But i guess typescript still js. It's not a framework or something like that. And js snippets still totally relevant.
May you please copy js snippets into typescript's json to make it consistent?
E.g in js snippets `console.log` is `cl` and in ts snippets its `log`. And so on.

**Comment by rafamadriz** [comment]
Hey, thanks for reporting this. 

Is typescript the exact same as JavaScript ? I don't work with typescript so I'm not sure, I know they are almost the same but I thought there were some minor differences in the syntax. I can make all the typescript snippets be the same as javascript but I need to be sure that it's not going to bring some problems where some snippets are not proper typescript syntax, or maybe some typescript exclusive snippets are deleted.

**Comment by koengommers** [comment]
I've run into a similar thing where I want to use the javascript snippets in typescript. All javascript is valid typescript. There are some situations where a type needs to be added, but it should be fine to have the javascript snippets available in typescript. The snippets in react.json and react-ts.json also seem to be identical.

What's the best way to make the javascript snippets available when filetype is typescript?

**Comment by timsofteng** [comment]
@rafamadriz any news about it?
I've can you please extande `typescript.json` with `javascript.json`?

**Comment by bryant-the-coder** [comment]
> @rafamadriz any news about it? I've can you please extande `typescript.json` with `javascript.json`?

So, you want js snippets in ts? Or ts snippets in js file?

**Comment by timsofteng** [comment]
@bryant-the-coder 
We need js snippets in ts.
The main idea is to have same js base snippets for all js-like files (ts, tsx, jsx) with their own snippets additionally.
Take a look at tsx and js snippets. There are a lot of differents in names in same snippets.
Like `console.log` is `cl` in js but it's `log` in tsx. And many snippets missed in tsx comparing to js.

**Comment by bryant-the-coder** [comment]
You can make a pr to fix that :))

**Comment by OkelleyDevelopment** [comment]
I actually think I have a fix for this

**Comment by bryant-the-coder** [comment]
nice nice

**Comment by timsofteng** [comment]
@OkelleyDevelopment 
Hello!
Sny updates around this issue?

**Comment by bobbyrahmanda13** [comment]
hello when will this update i need a javascript snippet for typescript, because typescript is not a language but a tool, please watch this video, https://www.youtube.com/watch?v=30LWjhZzg50&t=428s

**Comment by mauroporras** [comment]
This is what I did too: https://github.com/rafamadriz/friendly-snippets#add-snippets-from-a-framework-to-a-filetype

For those who want to copy and paste:

```lua
require'luasnip'.filetype_extend("typescript", { "javascript" })
```
