### ISSUE TITLE
Shellscript snippets don't seem to work with zsh

### ISSUE THREAD

**Issue by ItsDrike** [rafamadriz/friendly-snippets#107]
The title sums it all. 

With syntax set to shell or bash, the shell snippets are working well, however when it's set to zsh, these snippets aren't loaded.

**Comment by rafamadriz** [comment]
> With syntax set to shell or bash, the shell snippets are working well, however when it's set to zsh, these snippets aren't loaded.

Snippets are not going to extend to the file you want with the `set syntax` option. To extend `sh` snippets to the `zsh` filetype I recommend doing: 

NOTE:  this works if you use luasinp
```lua
require'luasnip'.filetype_extend("zsh", {"sh"})
```

**Comment by ItsDrike** [comment]
That's fair, but I was hoping that this could get implemented directly. There's probably no reason not to, if bash is automatically supported, why isn't zsh

**Comment by rafamadriz** [comment]
It's because the syntax differences, but sure I can add zsh to `sh` by default.
