### ISSUE TITLE
Help: Not sure how to use this plugin

### ISSUE THREAD

**Issue by thebluelake** [rafamadriz/friendly-snippets#110]
Hi,

I'm a bit confused on how to use this plugin. I've installed this using packer like so
```
 use "radamadriz/friendly-snippets"
 use({
    "L3MON4D3/LuaSnip",
    config = function()
      require("plugins.lua_snip")
    end,
  })
```

If I want completions for snippets in the c.json file do I just add this line to the lua_snip.lua file?
```
require("luasnip").filetype_extend("c", { "c" })
```

What about for frameworks like vue?

**Comment by zeitchef** [comment]
I also think a clear setup/configuration example would be highly useful.

**Comment by rafamadriz** [comment]
@thebluelake to setup completion you need to do that with whatever completion plugin you're using. I'd recommend https://github.com/hrsh7th/nvim-cmp. 

> If I want completions for snippets in the c.json file do I just add this line to the lua_snip.lua file?
> `require("luasnip").filetype_extend("c", { "c" })`

You don't need to do that for C files, if you've setup completion with your plugin of choice it should be automatic. Snippets are added by default to all languages. The only thing not added by default are frameworks. 

> What about for frameworks like vue?

For frameworks you need to extend them to the file you want. For example: if you want to add Vue snippets to the javascript filetype do the following:

```lua
require("luasnip").filetype_extend("javascript", { "vue" })
```

**Comment by rafamadriz** [comment]
> @zeitchef  I also think a clear setup/configuration example would be highly useful.

Maybe that could be added to the wiki, this is just a snippet collection. How you set it up may depend on what completion and snippet plugin you use. Or maybe you only use the snippet plugin and don't want completion, my point being there's a ton of options.

**Comment by thebluelake** [comment]
> @thebluelake to setup completion you need to do that with whatever completion plugin you're using. I'd recommend https://github.com/hrsh7th/nvim-cmp.
> 
> > If I want completions for snippets in the c.json file do I just add this line to the lua_snip.lua file?
> > `require("luasnip").filetype_extend("c", { "c" })`
> 
> You don't need to do that for C files, if you've setup completion with your plugin of choice it should be automatic. Snippets are added by default to all languages. The only thing not added by default are frameworks.
> 
> > What about for frameworks like vue?
> 
> For frameworks you need to extend them to the file you want. For example: if you want to add Vue snippets to the javascript filetype do the following:
> 
> ```lua
> require("luasnip").filetype_extend("javascript", { "vue" })
> ```

I see thank you! It works now.

**Comment by kahnclusions** [comment]
An explanation in the README would help a lot... I am really confused about how to make this work. How do other plugins know how to load the snippets from this repo? Are they just supposed to directly reference to files in my `~/.local/share/nvim/site/pack/packer/start/friendly-snippets/`?
