### ISSUE TITLE
LuaSnippet support

### ISSUE THREAD

**Issue by leiserfg** [rafamadriz/friendly-snippets#14]
This is an announcement more than an issue. Since some weeks ago https://github.com/L3MON4D3/LuaSnip also works with these snippets.

**Comment by rafamadriz** [comment]
hey thanks for letting know that. However I couldn't make the snippets work with LuaSnip. Could you share how you did it ?

**Comment by leiserfg** [comment]
These are my snippets:
https://github.com/leiserfg/dots/blob/master/.config/nvim/lua/my/snippets.lua
As you see you have to do
```lua
require('luasnip/loaders/from_vscode').load()
```
after defining your own snippets.

**Comment by rafamadriz** [comment]
Okay after testing once again with LuaSnip I did manage to make them work, however for some reason adding `require('luasnip/loaders/from_vscode').load()` doesn't work for me, I have to execute that in the command mode with `lua require...` and after that they would work. And also I guess that it's still work in progress; snippets with multiple selections/options wouldn't work, and the integration with nvim_compe isn't as good yet, the preview for the snippet doesn't properly show up in nvim-compe and sometimes it doesn't even show.

However I'm gonna look forward for LuaSnip, I want to replace vsnip for one made in Lua, the potential of having snippets made in Lua (and all of the benefits it brings) but also being able to load snippets with the vscode format seems pretty awesome and powerful, but I'm gonna wait until the integration with nvim-compe and loading vscode snippets works better.
