### ISSUE TITLE
Looking for new collaborators/maintainers

### ISSUE THREAD

**Issue by rafamadriz** [rafamadriz/friendly-snippets#144]
If anyone wants to help let me know.

**Comment by bryant-the-coder** [comment]
what happened to u? just asking

**Comment by OkelleyDevelopment** [comment]
What would be the expectations of new collaborators/ maintainers?

**Comment by rafamadriz** [comment]
@bryant-the-coder @OkelleyDevelopment Nothing really, just don't have a lot of time free time. It's not like this is difficult to maintain (it's just a bunch of json files) but I want to give other people write access so they can also merge PRs and push fixes. 

The only thing that people who wants to help should know is that I want to keep the default experience as vanilla as possible. What I mean is that by default, snippets from specific frameworks, packages, or whatever shouldn't be added by default. For example look at PR #128, which adds snippets for a specific latex package. Most users are not going to be using that package, so it shouldn't be added by default, and that's way the frameworks folder exist. So we can add snippets from frameworks and people can extend them if needed. Point being, default experience should be snippets for the vanilla language. 

The other thing I've been thinking of doing, is a little bit of a clean up. I feel like some languages have way to many snippets, maybe we can reduce them a little bit.

**Comment by OkelleyDevelopment** [comment]
@rafamadriz My next couple weeks are heavily booked, however, I am open to helping out as I  
can

**Comment by bryant-the-coder** [comment]
@rafamadriz i am free :)) i am also willing to help

**Comment by rafamadriz** [comment]
@OkelleyDevelopment @bryant-the-coder I invited both of you as collaborators. Thanks!
