### ISSUE TITLE
Can we add JSDoc snippets?

### ISSUE THREAD

**Issue by EdgarOrtegaRamirez** [rafamadriz/friendly-snippets#150]
https://github.com/honza/vim-snippets/blob/master/UltiSnips/javascript-jsdoc.snippets

**Comment by OkelleyDevelopment** [comment]
@bryant-the-coder Do you think we should include these? I'm not really in favor, but don't want to shut it down without some other input.

**Comment by bryant-the-coder** [comment]
yes we can add it @OkelleyDevelopment

**Comment by OkelleyDevelopment** [comment]
@EdgarOrtegaRamirez  Open a PR then will review it and add them to the collection

**Comment by bryant-the-coder** [comment]
@EdgarOrtegaRamirez check #168
