### ISSUE TITLE
Access React Snippets in Gatsby Projects

### ISSUE THREAD

**Issue by anoopd** [rafamadriz/friendly-snippets#154]
Right now only `javascript` snippets are available for Gatsby projects since the filetype is javascript. Is it possible to acces `javascriptreact` snippets inside Gatsby ?

**Comment by OkelleyDevelopment** [comment]
Yes, one way I found would be like this : 
![image](https://user-images.githubusercontent.com/56930510/168967798-9131e8cd-b358-488e-82eb-e99608068a65.png)

Which I also shared on [issue #100 ](https://github.com/rafamadriz/friendly-snippets/issues/100#issuecomment-1126645107)

I haven't personally used the other snippet tools, but would wager it should be a similar approach 

Hope this helps :smile:

**Comment by anoopd** [comment]
@OkelleyDevelopment   Thank you for the suggestion , will try it and let you know whether it works or not .

**Comment by OkelleyDevelopment** [comment]
Awesome to hear @anoopd !  :partying_face: 

I'm going to close this issue but should anything else come up feel free to open another / reopen this one :mechanical_arm:
