### ISSUE TITLE
Fixing duplicate snippets in javascript.json

### ISSUE THREAD

**Issue by rafamadriz** [rafamadriz/friendly-snippets#16]
Remove duplicate snippets in https://github.com/rafamadriz/friendly-snippets/blob/main/snippets/javascript/javascript.json

**Comment by motorto** [comment]
I don't mind doing it. 

Currently I have found this repeated:

* setTimeout and Set Timeout Function
* setInterval and Set Interval Function 

I will update once I found more, but if you guys find some I will added it here and it would make my life easier :)

(Should I pull request what I have done already ? @rafamadriz  )

**Comment by rafamadriz** [comment]
> (Should I pull request what I have done already ? @rafamadriz )

Sure, you can make a PR if you want. Thanks!
