### ISSUE TITLE
Can we add Dockerfile snippets ?

### ISSUE THREAD

**Issue by monster898** [rafamadriz/friendly-snippets#169]
I love friendly-snippets! Thanks to amazing maintainers! 

Is it possible to add Dockerfile snippets? Like this one below:

https://github.com/ekalinin/Dockerfile.vim/tree/master/snippets

**Comment by OkelleyDevelopment** [comment]
Hello! :wave: I don't see any reason why those couldn't be mirrored here 

@bryant-the-coder  any objections?

**Comment by bryant-the-coder** [comment]
interesting idea you got there @monster898. You can add em by creating a pr :)

**Comment by OkelleyDevelopment** [comment]
I have some time tonight that I should be able to finish this up

**Comment by OkelleyDevelopment** [comment]
After test driving this some more, there are a few things I want to correct (duplicates between what already exists)
