### ISSUE TITLE
php snippets not entirely consistent: function and class have braces on new line

### ISSUE THREAD

**Issue by onno-schuit** [rafamadriz/friendly-snippets#177]
In snippet/php.json, the K&R formatting style is followed, except for 'function' and 'class', which have their open brace start on a new line.

**Comment by OkelleyDevelopment** [comment]
Hello :wave:  

I've had busy last week, but I will do my best to resolve this in the next couple days. :sunglasses:

**Comment by onno-schuit** [comment]
Hi, thanks for all your efforts. I know maintaining OSS Git repos can be very time consuming (I've done a tiny one myself), so this is much appreciated!

**Comment by oldy777** [comment]
@OkelleyDevelopment Hi! 
I think it was bad decision due to [PSR-2 ](https://www.php-fig.org/psr/psr-2/)

Maybe it will be good to revert changes and make snippets more relevant to PSR and php 8.(2,3) syntax?
What do you think?
