### ISSUE TITLE
How to overwrite some snippets

### ISSUE THREAD

**Issue by ArnoldWolfstein** [rafamadriz/friendly-snippets#189]
Hi there,

How can we overwrite some snippets that come from the repo? E.g. I want to overwrite `function` prefix in `shell` snippets.
In my custom user `shell.json` snippet file, I give priority **2000** to my snippet, but it seems it doesn't work.

```json
{
  "function": {
    "prefix": "function",
    "body": "${1:some_name} ()\n{\n\t${0}\n}",
    "description": [
      "Something something\n",
    ]
    "luasnip": {
      "priority": 2000,
      "autotrigger": true
    }
  },
}
```

**Comment by OkelleyDevelopment** [comment]
Hey @ArnoldWolfstein  any updates on the status of this? (Did you figure anything out / what leads have you looked into/ etc) 

Let us know and then we can get more organized on trying to solve the issue

Cheers :sunglasses:

**Comment by OkelleyDevelopment** [comment]
I finally had a moment to investigate this myself and after testing the snippet myself, I was able to get the snippets to load when I removed the following line: 
```json
"autotrigger": true,
```

Currently this *does not seem to handle priority* of the snippets, but I will see what I can find in their documentation.

**Comment by OkelleyDevelopment** [comment]
Fun fact: after closing neovim and coming back to this after dinner. Priority was working :sunglasses:

**Comment by OkelleyDevelopment** [comment]
Hello again @ArnoldWolfstein !  

### Context

I did some digging and after asking [here](https://github.com/L3MON4D3/LuaSnip/issues/627), learned that if you're using `nvim-cmp` and `cmp_luasnip` for completions then the snippets *will not expand in the completion listing*.

However, the snippet still shows via `:LuaSnipListAvailable` meaning it is being read though the [PR for autosnippet support](https://github.com/saadparwaiz1/cmp_luasnip/pull/27) via `cmp_luasnip` is still under development. 

### Answer to the original question:
> How can we overwrite some snippets that come from the repo? E.g. I want to overwrite function prefix in shell snippets.

Based on my testing, if you are using `nvim-cmp` and `cmp_luasnip` then remove the `autotrigger` line from your custom snippet and it should load in first:


```json
{
  "function": {
    "prefix": "function",
    "body": "${1:some_name} ()\n{\n\t${0}\n}",
    "description": [
      "Something something\n",
    ]
    "luasnip": {
      "priority": 2000
    }
  },
}
```


I hope this helps clarify things a bit. 

I'm going to close this issue, however, if you questions/concerns feel free to reopen this issue or create another one and I will see what I can do to help. :sunglasses:
