### ISSUE TITLE
C++ snippets stopped working

### ISSUE THREAD

**Issue by ghillb** [rafamadriz/friendly-snippets#190]
I noticed today, that C++ snippets stopped working for me. This message appears, when entering insert mode the first time, in a C++ file.
```
{'throwpint': 'TextChangedI Autocommands for "*"..function vsnip#get_complete_items[4... "body": ["__interface I${1:Interface}", "{", "\t$0", "};"],^@    "description": "C'}
```
It might have something to do with this recent commit: https://github.com/rafamadriz/friendly-snippets/commit/7dc25b370122fee0ebacb9d250b8fabe33069ac7?

**Comment by OkelleyDevelopment** [comment]
Hello @ghillb , it does appear that a few commas had been left out. Though there is a PR (#188) that I just tested locally that seems to resolve this issue.

**Comment by OkelleyDevelopment** [comment]
Just pulled main and it appears they are working again :raised_hands: 

![image](https://user-images.githubusercontent.com/56930510/185502201-5f4846d7-22f5-49ed-a987-679574cd7b40.png)
