### ISSUE TITLE
C/C++ #define snippet

### ISSUE THREAD

**Issue by ii14** [rafamadriz/friendly-snippets#2]
[snippets/c.json#L87](https://github.com/rafamadriz/friendly-snippets/blob/cb1900b0f1faf0f8bd2acdee24254c64c4966de5/snippets/c.json#L87), [snippets/cpp.json#L257](https://github.com/rafamadriz/friendly-snippets/blob/cb1900b0f1faf0f8bd2acdee24254c64c4966de5/snippets/cpp.json#L257)

```
  "#def": {
    "prefix": "#def",
    "body": ["#define \"$1\" \"$2\" "],
    "description": "Code snippet for #define \" \""
  },
```

I believe this is incorrect. Macro names cannot be quoted. It should be just `"#define $1 $2"`.

**Comment by rafamadriz** [comment]
Yes, you're right, it shouldn't be quoted. It's been fixed and also I noticed that when you started typing with `#` and you selected the snippet the shebang would get duplicate giving you `##define` instead of `#define`, that's been fixed too. Now the prefix is just `def`.

Thanks for reporting.
