### ISSUE TITLE
Ruby's `if else end` snippet can match while typing out `else`

### ISSUE THREAD

**Issue by technicalpickles** [rafamadriz/friendly-snippets#209]
I filed this on https://github.com/VonHeikemen/lsp-zero.nvim/issues/61 because that is what I was using, and wasn't sure where to file this. @VonHeikemen suggested filing here.

I'm working in ruby, and go to write an if/else statement, but I don't use the snippet. I can do the `if` fine like this, but as soon as I go to do the `else`, the `if else` snippet starts matching. If I press enter, then that snippet is triggered, and it ends up creating a second if statement instead of let

![CleanShot 2022-11-22 at 11 11 30](https://user-images.githubusercontent.com/159/203364468-8299c02d-4ed4-4bc7-b671-b1199d7eed09.gif)

It seems like typing `else` should only match snippets that match `else`, rather than ones that end in it.

My configuration:

```lua
local lsp = require("lsp-zero")

lsp.preset("recommended")
lsp.nvim_workspace()

lsp.setup()
```

I think the main reason for this is the snippet is named `if else`, with a space in it. Compare this to [vim-snippets](https://github.com/honza/vim-snippets) which calls this snippet `ife` as one word. This prevents it from matching tab completions  for typing `else`.

**Comment by OkelleyDevelopment** [comment]
Hello @technicalpickles :wave: 

I will do my best to investigate this issue tonight, but it might be tomorrow before you hear back (just depends on my other commitments). 

Resolving this issue might be as simple as just changing the prefix for the snippet. Will keep updates here as they happen :sunglasses:

**Comment by OkelleyDevelopment** [comment]
Hey @technicalpickles ! 

Hope things are well, I've done some digging and now have a PR open with the proposed changes which essentially just changes the naming of the if-else statement `prefix`es.  

I was hoping to have you check the changes (and potentially load them in your config via the PR's testing guide) just as a second set of eyes on it. 

Let me know if you have any questions or concerns with the changes :sunglasses:

**Comment by technicalpickles** [comment]
This looks much better, thanks!

**Comment by OkelleyDevelopment** [comment]
Hooray! :partying_face:  

I went ahead and merge it here, so it should be available to you now. Have fun building away!
