### ISSUE TITLE
Need to escape CurlyClose?

### ISSUE THREAD

**Issue by octaltree** [rafamadriz/friendly-snippets#23]
https://github.com/rafamadriz/friendly-snippets/blob/22c37fd12074290561210004918a870db085ceb3/snippets/lua.json#L32
I don't use vscode, so I'm not familiar with it, but wouldn't you need to escape '}' here?

**Comment by rafamadriz** [comment]
I don't think so, I get my snippet as expected. 
![2021-Jun-13](https://user-images.githubusercontent.com/67771985/121813648-7c55fe00-cc5c-11eb-862b-20072cd78fe8.png)

**Comment by octaltree** [comment]
Sorry, I must have misread [the parser implementation](https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/snippet/snippetParser.ts).
