### ISSUE TITLE
Prevent specific snippets from being used/ or override them

### ISSUE THREAD

**Issue by jrwrigh** [rafamadriz/friendly-snippets#243]
The C snippets are great, but all the for loop snippets have the `++` and `--` on the wrong side for my style tastes (and the ones of my projects). Is there a way to delete these snippets from being loaded with LuaSnip? Or a way to overwrite them?

**Comment by OkelleyDevelopment** [comment]
I think this might be worth opening a PR to correct the ordering of the increment/decrement. 

However to answer you question, you can create the snippets you want in a local snippets directory and source them in the config something akin to this:

```lua
require("luasnip/loaders/from_vscode").load { paths = "/home/<user name here>/.config/nvim/snippets" }
```

Then for the snippets you want to override, format it like 
```json
{
  "function": {
    "prefix": "function",
    "body": "${1:some_name} ()\n{\n\t${0}\n}",
    "description": [
      "Something something\n",
    ]
    "luasnip": {
      "priority": 2000
    }
  },
}
```

I believe that so long as the `priority` is > 500, it should load as one of the top snippets. 

To prevent the snippets from loading entirely ... at this moment in time I don't know how to do that :sweat_smile:
