### ISSUE TITLE
Angular snippets

### ISSUE THREAD

**Issue by joeveiga** [rafamadriz/friendly-snippets#266]
Hello!

Would you be open to adding [these Angular snippets](https://github.com/johnpapa/vscode-angular-snippets/tree/main/snippets) to the supported frameworks?

Thanks!

**Comment by OkelleyDevelopment** [comment]
Hey @joeveiga, feel free to open a pull request with the ones you'd like

**Comment by OkelleyDevelopment** [comment]
This [PR](https://github.com/rafamadriz/friendly-snippets/pull/355) addresses this issue. Thanks @sirstanislav :raised_hands:
