### ISSUE TITLE
JSDoc snippet doesn't work

### ISSUE THREAD

**Issue by rwxmad** [rafamadriz/friendly-snippets#269]
The snippet for adding a comment still doesn't work

![Screenshot 2023-03-27 at 09 57 29](https://user-images.githubusercontent.com/30772868/227864541-a7b8c9a8-c329-4d03-98f5-fefb8091fd24.png)

![Screenshot 2023-03-27 at 09 59 33](https://user-images.githubusercontent.com/30772868/227864549-f0e1533c-4362-4e7b-aa34-ec36f11612f9.png)

///
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Ventura-arm64.local
///

**Comment by OkelleyDevelopment** [comment]
Hey @rwxmad , did you add this line to your config? 
```lua
require("luasnip").filetype_extend("javascript", { "jsdoc" })
```

**Comment by rwxmad** [comment]
> Hey @rwxmad , did you add this line to your config?
> 
> ```lua
> require("luasnip").filetype_extend("javascript", { "jsdoc" })
> ```

thanks a lot, this solved my problem
