### ISSUE TITLE
Disable snippets for certain language.

### ISSUE THREAD

**Issue by Fr4nk1in-USTC** [rafamadriz/friendly-snippets#271]
I have my own LaTeX snippets and they have conflicts with friendly-snippets, which is quite annoying. Is there a way to disable friendly-snippets for LaTeX?

**Comment by pycgarcia** [comment]
I'm interested in this feature as well, there's a "." snippet in python. Is really annoying.

**Comment by razzat008** [comment]
> Is there a way to disable friendly-snippets for LaTeX?

You can delete the latex.json file in ~/.local/share/nvim dir. This will cause the luasnip to source from your own snippets.

---
*MAKE SURE TO BACKUP BEFORE DOING SO*

**Comment by rafamadriz** [comment]
@Fr4nk1in-USTC This is done with your snippet engine, if using luasnip see `:help luasnip-loaders`:

```lua   
require("luasnip.loaders.from_vscode").load {
        exclude = { "plaintex", "tex" },
    }
```

> I'm interested in this feature as well, there's a "." snippet in python. Is really annoying.

@pycgarcia Latest commit bf3c6b2d should fix it
