### ISSUE TITLE
Is shellscript meant to work for *.sh files?

### ISSUE THREAD

**Issue by thepenguinthatwants** [rafamadriz/friendly-snippets#28]
Hi,
I couldn't get the bash snippets to work on *.sh named files.
But they do seem to work with python.

Using luasnip so wondering if the shellscript is meant to be used for bash scripts.

**Comment by rafamadriz** [comment]
Yes, snippets from [shell](https://github.com/rafamadriz/friendly-snippets/blob/main/snippets/shell.json) are meant to work with sh files. I just tested and they work for me.

**Comment by thepenguinthatwants** [comment]
Wondering how to get this more verbose, as they are not appearing at all.

**Comment by thepenguinthatwants** [comment]
Weird I gotten it to work after switching the package.json from language shellscript to sh or shell.

**Comment by rafamadriz** [comment]
> Weird I gotten it to work after switching the package.json from language shellscript to sh or shell.

mmmm... yeah that's weird. Thanks for letting me know, I'll add sh and shell to the language in case anyone else has your problem.
