### ISSUE TITLE
powershell.json is not picked up by snippet

### ISSUE THREAD

**Issue by sandeep-ad** [rafamadriz/friendly-snippets#283]
Since plugin is missing powershell snippets so I copied the json file from  `https://github.com/PowerShell/vscode-powershell/blob/main/snippets/PowerShell.json` and placed along with other files at `nvim-local/site/pack/packer/start/friendly-snippets/snippets`. Finally updated package.json to include powershell.
      {
        "language": [
          "PowerShell",
          "ps1"
        ],
        "path": "./snippets/powershell.json"
      },

However, when I create file.ps1 and try to list available snippets I do see   `ps1 = {}`

**Comment by rafamadriz** [comment]
Are you getting snippets in other languages ? Is this path `nvim-local/site/pack/packer/start/friendly-snippets/snippets` in the runtime? If not you will not get snippets

**Comment by rafamadriz** [comment]
PowerShell snippets were added, and they work for me, reopen if any issue

**Comment by sandeep-ad** [comment]
Here is the output of my runtimepath

runtimepath=~/.config/nvim
/usr/local/etc/xdg/nvim
/etc/xdg/nvim
~/.local/share/nvim/site
~/.local/share/nvim/site/pack/*/start/*
/usr/local/share/nvim/site
/usr/share/nv
im/site
/usr/local/Cellar/neovim/0.9.0/share/nvim/runtime
/usr/local/Cellar/neovim/0.9.0/share/nvim/runtime/pack/dist/opt/matchit
/usr/local/Cellar/neovim/0.9.0/lib/nvim
~/
.config/nvim/site/pack/*/start/*
~/.config/nvim/site/pack/packer/start/packer.nvim
~/.local/share/nvim/site/pack/*/start/*/after
/usr/share/nvim/site/after
/usr/local/share
/nvim/site/after
~/.local/share/nvim/site/after
/etc/xdg/nvim/after
/usr/local/etc/xdg/nvim/after
~/.config/nvim/after
$HOME/.config/coc/settings.json

When type luaSnipListAvailable I see following
![image](https://user-images.githubusercontent.com/110502966/235543039-47b470a7-5dfe-45dc-a4d4-95597a2159ed.png)

**Comment by rafamadriz** [comment]
Please try to reproduce with this [minimal config](https://github.com/rafamadriz/friendly-snippets/blob/main/debug/packer-nvim.lua), they work with that config. Use `nvim -u` to open neovim using that config instead of the default.

**Comment by sandeep-ad** [comment]
Awesome this works. Really appriciate it.
