### ISSUE TITLE
Friendly snippets failed in kickstart nvim config

### ISSUE THREAD

**Issue by SamPosh** [rafamadriz/friendly-snippets#284]
When i add friendly snippets in kickstart.nvim as below

{

-- Autocompletion

'hrsh7th/nvim-cmp',

dependencies = { 'hrsh7th/cmp-nvim-lsp',

'rafamadriz/friendly-snippets' ,

'L3MON4D3/LuaSnip',

'saadparwaiz1/cmp_luasnip',

},

},

below error is displaying

Error detected while processing /root/.config/nvim/init.lua:

Invalid plugin spec {

autoformat = true,

format = <function 1>,

on_attach = <function 2>,

toggle = <function 3>

}

How to correct it?

**Comment by rafamadriz** [comment]
The error is not related to friendly-snippets, I believe those are lazy.nvim errors.
