### ISSUE TITLE
Error with the just added terraform snippets

### ISSUE THREAD

**Issue by aleprovencio** [rafamadriz/friendly-snippets#294]
Hello, I'm getting this while editing terraform files:

```
2023-05-20T08:30:38 Messages  INFO Error executing lua callback: ...packer/start/LuaSnip/lua/luasnip/loaders/from_vscode.lua:54: bad argument #1 to 'concat' (table expected, got nil)
stack traceback:
	[C]: in function 'concat'
	...packer/start/LuaSnip/lua/luasnip/loaders/from_vscode.lua:54: in function 'get_file_snippets'
	...packer/start/LuaSnip/lua/luasnip/loaders/from_vscode.lua:100: in function 'load_snippet_files'
	...packer/start/LuaSnip/lua/luasnip/loaders/from_vscode.lua:271: in function '_load_lazy_loaded_ft'
	...packer/start/LuaSnip/lua/luasnip/loaders/from_vscode.lua:284: in function '_load_lazy_loaded'
	...e/nvim/site/pack/packer/start/LuaSnip/plugin/luasnip.lua:103: in function <...e/nvim/site/pack/packer/start/LuaSnip/plugin/luasnip.lua:102>
2023-05-20T08:30:38 Error  ERROR Erro detectado ao processar BufWinEnter Autocommands for "*":
```

Rolling back to `b248e8db97ab23b189e65cd0864db42c472bfc54` stops the error messages.

**Comment by snoord** [comment]
This error is caused by [the copyright object](https://github.com/rafamadriz/friendly-snippets/blob/f674dae71b9daf5ba4a4daf0734f7780417237b1/snippets/terraform.json#L6886-L6886) as it is missing the `body` field used by LuaSnip. Removing that line (and ensuring the resulting JSON file is syntactically correct) stops the error from occurring.

**Comment by rafamadriz** [comment]
For some reason I could not reproduce the problem, @aleprovencio let me know if latest commit fixes the problem. Thanks @snoord for the fix.

**Comment by aleprovencio** [comment]
Thanks for the input guys, but unfortunately this is still not a fix here.

When you first open a terraform file, the error will not show, but you can notice something is wrong because of the missing syntax highlighting.

After that if you open a file which is not a terraform one (like a `README.md` or maybe a `playbook.yml`) and then go back to that terraform file, now the error will pop up.
