### ISSUE TITLE
"Begin" snippet in latex seems wrong

### ISSUE THREAD

**Issue by mortang2410** [rafamadriz/friendly-snippets#297]
In latex (using nvim and LuaSnip with `jsregexp` ), when I use the "Begin" snippet to start an environment called `test`,  I get 
```tex
\begin{test}
  (?1:\item )(?2:\item)
\end{test}
```
Which is not expected behavior.  Looking at some examples given [here](https://stackoverflow.com/questions/57381007/vscode-if-else-conditions-in-user-defined-snippet?rq=1), I believe the correct version should be 
```json
  "\\begin{}…\\end{}": {
    "prefix": "begin",
    "body": [
      "\\\\begin{${1:env}}",
      "\t${1/(enumerate|itemize|list)|(description)|(.*)/${1:+\\item }${2:+\\item }${3:+ }/}$0",
      "\\\\end{${1:env}}"
    ],
    "description": "Begin - End"
  },
```
Similarly the `tab` snippet seems to suffer from this same problem.

**Comment by mangkoran** [comment]
I can reproduce the issue above.

https://github.com/rafamadriz/friendly-snippets/assets/57625126/43a59b24-e4ca-4bef-8f71-48b62a3893d0

**Comment by mangkoran** [comment]
@rafamadriz I have opened #314. Please take a look and let me know if there is anything that I should update.
