### ISSUE TITLE
Blade snippets

### ISSUE THREAD

**Issue by erizo-dev** [rafamadriz/friendly-snippets#299]
Hi,
would it be possible add laravel blade snippets. I have found those https://github.com/onecentlin/laravel-blade-snippets-vscode/tree/master/snippets which do seem to include both blade and livewire.
I have forked the repository.
Is there anything special I need to pay attention to if I wish to submit a Pr ? 
Kind regards

**Comment by OkelleyDevelopment** [comment]
Hey @erizo-dev feel free to open a PR. Generally when I'm reviewing PRs, I look for the following: 
- Are the snippets logical/ serve a strong utility or are properly abstracted (sometimes inferred from the description of the snippet)
- Are the typos? 
- Has the `package.json` at the root been updated to point to the new snippets (if necessary)
- Is this a repeat of other snippets not properly documented/easily found?

While it's not possible for one person to know all programming languages, I've found at least meeting these four points in a review yields the best results. 

If you get stuck/have concerns feel free to open a draft PR and ping for help!
