### ISSUE TITLE
Vue snippets

### ISSUE THREAD

**Issue by timsofteng** [rafamadriz/friendly-snippets#3]
Could you please add snippets for vue?

**Comment by rafamadriz** [comment]
## Added snippets for Vue files. Take a look to the [wiki](https://github.com/rafamadriz/friendly-snippets/wiki/Vue) for a complete list.

![2021-Mar-29](https://user-images.githubusercontent.com/67771985/112915259-70db4800-90ed-11eb-91d8-6dd5aab82b35.png)
![2021-Mar-29_2](https://user-images.githubusercontent.com/67771985/112915266-73d63880-90ed-11eb-8586-bea688a699ab.png)
![2021-Mar-29_1](https://user-images.githubusercontent.com/67771985/112915263-72a50b80-90ed-11eb-9887-2a48ab83f6f6.png)
