### ISSUE TITLE
compe's first popup makes insert mode freeze or laggy 

### ISSUE THREAD

**Issue by siduck76** [rafamadriz/friendly-snippets#30]
Hi there! great plugin. Ive been having this issue that compe's first popup ( autocompletion menu ) freezes or completely gets stuck for some seconds but this happens only for the first time and works fine later. 

behaviour : 

https://user-images.githubusercontent.com/59060246/123509382-c7c3cf80-d692-11eb-9163-185e336ce816.mp4

**Comment by siduck76** [comment]
I removed plugins one by one and found out friendly-snippets was causing this.

**Comment by Samantha-uk** [comment]
> I removed plugins one by one and found out friendly-snippets or vim vsnip both cause this.

Might it be that they are only lazy loading the snippets the first time you try to use them?

**Comment by siduck76** [comment]
> > I removed plugins one by one and found out friendly-snippets or vim vsnip both cause this.
> 
> Might it be that they are only lazy loading the snippets the first time you try to use them?

no this happens without lazy loading too :(

**Comment by siduck76** [comment]
my latest config has lazy loading , this happened before it too.

**Comment by siduck76** [comment]
@Samantha-uk seems like the issue is with vsnip , I tried using my friend's luasnip config and it fixed the issue but the luasnip config was huge :/ .

**Comment by siduck76** [comment]
NVM the issue has been fixed by using luasnip instead of vsnip :D

**Comment by rafamadriz** [comment]
@siduck76 I also have the same problem, a minor lag when you first start typing, really annoying.  

> seems like the issue is with vsnip , I tried using my friend's luasnip config and it fixed the issue but the luasnip config was huge :/ . vsnip works with no config but initial lag

Yes, this is because of vsnip. At the end of the day this is just a snippet collection, it doesn't have any code logic or anything, just json files.
