### ISSUE TITLE
Populate Key Value pair for json files

### ISSUE THREAD

**Issue by nippyin** [rafamadriz/friendly-snippets#312]
Is there a way I get snippet trigger when type {} while editing json file in nvim?
```
        {
          "key": "value"
        },

```

**Comment by OkelleyDevelopment** [comment]
Are you trying to trigger a particular snippet are just wanting the curly braces to expand?

**Comment by OkelleyDevelopment** [comment]
Closing since no further discussion has happened. Feel free to reopen if you still need assistance :sunglasses:
