### ISSUE TITLE
[READY]: standardized code comments

### ISSUE THREAD

**Issue by Zeioth** [rafamadriz/friendly-snippets#327]
This is an effort to implement the official specification of code comments for the most extended programming languages.

## Already implemended

* [typescript](https://github.com/rafamadriz/friendly-snippets/pull/301) (merged) → Reviewed, tested, and working
* [javascript](https://github.com/rafamadriz/friendly-snippets/pull/303) (merged) → Reviewed, tested, and working
* [c#](https://github.com/rafamadriz/friendly-snippets/pull/308) (merged) → Reviewed, tested, working
* [luadoc](https://github.com/rafamadriz/friendly-snippets/pull/307) (merged) → Reviewed, tested, and working
* [python](https://github.com/rafamadriz/friendly-snippets/pull/330) (merged) → Reviewed, tested, and working
* [rust](https://github.com/rafamadriz/friendly-snippets/pull/318) (merged) → Reviewed, tested, and working
* [java](https://github.com/rafamadriz/friendly-snippets/pull/321) (merged) → Reviewed, tested and working
* [shell](https://github.com/rafamadriz/friendly-snippets/pull/325) (merged) → Reviewed, tested and working
* [c](https://github.com/rafamadriz/friendly-snippets/pull/326) (merged) → Reviewed, tested and working
* [c++](https://github.com/rafamadriz/friendly-snippets/pull/336) (merged) → Reviewed, tested and working
* [php](https://github.com/rafamadriz/friendly-snippets/pull/332) (merged) → Reviewed, tested and working
* [kotlin](https://github.com/rafamadriz/friendly-snippets/pull/333)(merged) → Reviewed, tested and working
* [ruby](https://github.com/rafamadriz/friendly-snippets/pull/334)(merged) → Reviewed, tested and working

## Coming probably never
* dart → Fuck you google
* go
* Objetive-C  → Fuck you apple
* swift

## How to enable it
This is an example for neovim lazy.nvim

```lua
{
  "L3MON4D3/LuaSnip",
  build = vim.fn.has "win32" ~= 0
      and "echo 'NOTE: jsregexp is optional, so not a big deal if it fails to build\n'; make install_jsregexp"
    or nil,
  dependencies = {
    "zeioth/friendly-snippets", -- change to rafamadriz once all is merged
    "benfowler/telescope-luasnip.nvim",
  },
  config = function(_, opts)
    if opts then require("luasnip").config.setup(opts) end
    vim.tbl_map(
      function(type) require("luasnip.loaders.from_" .. type).lazy_load() end,
      { "vscode", "snipmate", "lua" }
    )
    -- friendly-snippets - enable standardized comments snippets
      require("luasnip").filetype_extend("typescript", { "tsdoc" })
      require("luasnip").filetype_extend("javascript", { "jsdoc" })
      require("luasnip").filetype_extend("lua", { "luadoc" })
      require("luasnip").filetype_extend("python", { "pydoc" })
      require("luasnip").filetype_extend("rust", { "rustdoc" })
      require("luasnip").filetype_extend("cs", { "csharpdoc" })
      require("luasnip").filetype_extend("java", { "javadoc" })
      require("luasnip").filetype_extend("c", { "cdoc" })
      require("luasnip").filetype_extend("cpp", { "cppdoc" })
      require("luasnip").filetype_extend("php", { "phpdoc" })
      require("luasnip").filetype_extend("kotlin", { "kdoc" })
      require("luasnip").filetype_extend("ruby", { "rdoc" })
      require("luasnip").filetype_extend("sh", { "shelldoc" })
  end,
},
```

**Comment by Zeioth** [comment]
## Update on Dart

* No point in us implementing DartDoc snippets unless they remove this against standards atrocity.

![screenshot_2023-06-13_11-07-40_668743683](https://github.com/rafamadriz/friendly-snippets/assets/3357792/0f9aff81-2dd8-46bd-9a56-0a1a9ddca7a3)

**Comment by Zeioth** [comment]
All languages I initially planed to implement are ready. I'll be self-reviewing them until the 15 on june, and after date I will step away, so you can merge without interferences.

**Comment by REmerald** [comment]
@Zeioth, is there any reason to have it like
```
" * @example",
" * // ${6:Description of my example.}",
" * ${7:Write me later}",
```
instead of
```
" * @example",
" * ${6:Description of my example.}",
" * ${7:Write me later}",
```
in c, cpp, php?

[Doxygen doesn't seem to recommend it.](https://www.doxygen.nl/manual/commands.html#cmdexample)

**Comment by Zeioth** [comment]
@REmerald  Doxygen is gonna render `@example` as a block of code. By adding //, the example description is gonna appear as a code comment in the generated HTML.

The idea with full block comments is to provide a template to use as reference. Most users will delete a field or another. Which is why we also provide simple comment blocks, for users who prefer to add tags manually.

**Comment by REmerald** [comment]
@Zeioth, thx, now i get it.

**Comment by surmish** [comment]
How are snippets in cppdoc.json triggered?

E.g. I see this in a recent merge (cppdoc.json)

```json
{
    "comment": {
        "prefix": "/**",
        "body": [
            "/**",
            " * ${1:A one-line summay.}",
            " *",
            " * ${2:Description.}$0",
            " *",
            " * @param ${4:name} ${5:Type and description of the parameter.}",
            " * @return ${3:Type and description of the returned value.}",
            " *",
            " * @example",
            " * // ${6:Description of my example.}",
            " * ${7:Write me later}",
            " */"
        ],
        "description": "A C++ comment block for functions, including description, param, return, and example."
    },
}
```

However when I open a file (filetype cpp) and type in `/**`, I don't see snippet suggestions. Is this for a different file type? I use the www.github.com/LazyVim/LazyVim config (largely default configs w.r.t code completion) and friendly-snippets.

**Comment by rafamadriz** [comment]
@surmish  This should work `require'luasnip'.filetype_extend("cpp", {"cppdoc"})`.  I like it more this way because I want to keep the default experience for snippets as vanilla as possible. And alternatively, if users want to add other snippets (like from frameworks or docs in this case) they can extend it.

**Comment by OkelleyDevelopment** [comment]
@Zeioth is the commit above still accurate, meaning we can close this issue now?

**Comment by Zeioth** [comment]
@OkelleyDevelopment thank you for the merge!! Yes, we finally did it!!!

**Comment by Zeioth** [comment]
Maybe adding it to the wiki would be a good idea so people can discover the feature.

**Comment by OkelleyDevelopment** [comment]
I'll reopen this issue temporarily to remind me to update the wiki with your steps from above (on mobile at the moment :sweat_smile: )

**Comment by OkelleyDevelopment** [comment]
Updated, feel free to re-open if there is context missing. :sunglasses:

**Comment by REmerald** [comment]
@Zeioth `"""*` snippets in `pydoc` are nearly unusable because of an autopairs plugin: there will always be a trailing `"` unless you typed `"` exactly 2 times before confirming the snippet.

**Comment by madjxatw** [comment]
How to make this work with the neovim builtin snippets.
