### ISSUE TITLE
How to disable final jump behind the snippet?

### ISSUE THREAD

**Issue by Exlll** [rafamadriz/friendly-snippets#342]
I'm currently programming in Rust and I'd like to disable the final jump for snippets that expand to multiple lines. For example, the snippet for structs is defined as 

```json
"struct": {
    "prefix": "struct",
    "body": [
        "#[derive(Debug)]",
        "struct ${1:Name} {",
        "    ${2:field}: ${3:Type}",
        "}"
    ],
    "description": "struct … { … }"
},
```

which expands to

```rust
#[derive(Debug)]
struct Name {
    field: Type
}
```

Now, if I press `<TAB>` multiple times the cursor first jumps to, `Name`, then to `field`, then to `Type`, and then, on the last jump, behind the closing `}`. Is there a way to disable this last jump? Preferably only for snippets that expand to multiple lines, as I find that behavior useful for single-line snippets like `print`, etc.

**Comment by Zeioth** [comment]
Using `$0` you can decide where the cursor go after all jumps are completed. [Example](https://github.com/rafamadriz/friendly-snippets/blob/8f5db6c5b691a6bbaa5dabd9afeb164ef8a06d04/snippets/c/cdoc.json#L64).

**Comment by Exlll** [comment]
@Zeioth Thank you very much! I replaced `${3:...}` with `${0:...}` and now it works the way I wanted. The JSON from my example above now looks like this:

```json
  "struct": {
    "prefix": "struct",
    "body": [
      "#[derive(Debug)]",
      "struct ${1:Name} {",
      "    ${2:field}: ${0:Type}",
      "}"
    ],
    "description": "struct … { … }"
  },
```
