### ISSUE TITLE
Python Docstring

### ISSUE THREAD

**Issue by huyhoang8398** [rafamadriz/friendly-snippets#350]
Is this possible to have this snippet for function and docstring python

**Comment by Zeioth** [comment]
@huyhoang8398 Did you check [here](https://github.com/rafamadriz/friendly-snippets/issues/327)?

I think what you are looking for is `require("luasnip").filetype_extend("python", { "python-docstring" })`

**Comment by huyhoang8398** [comment]
Yes,
I tried to add 
`require("luasnip").filetype_extend("python", { "python-docstring" })`
but tripple """ didnt work for me
howerver 
`require("luasnip").filetype_extend("sh", { "shelldoc" })` is working well

**Comment by Zeioth** [comment]
@huyhoang8398 There is something miss configured in your end then. I can see them correctly.
![screenshot_2023-08-06_12-36-56_948086424](https://github.com/rafamadriz/friendly-snippets/assets/3357792/ed346ffa-2f22-40a7-9b9a-74e545b69e17)

**Comment by huyhoang8398** [comment]
https://github.com/huyhoang8398/dotfiles/blob/macos/.config/nvim/lua/kn/plugins/configs/cmp.lua#L8

That's weird for me. Since for shellscript docstring works well. Not sure about python. Above is my configuration
Do i need to install any extra python dependency for that?

**Comment by Zeioth** [comment]
I see you are loading the vscode loader. Try adding also snipmate and lua like here:

```lua
{
  "L3MON4D3/LuaSnip",
  dependencies = {
    "rafamadriz/friendly-snippets",
    "benfowler/telescope-luasnip.nvim",
  },
  config = function(_, opts)
    if opts then require("luasnip").config.setup(opts) end
    vim.tbl_map(
      function(type) require("luasnip.loaders.from_" .. type).lazy_load() end,
      { "vscode", "snipmate", "lua" }
    )
    -- friendly-snippets - enable standardized comments snippets
    require("luasnip").filetype_extend("typescript", { "tsdoc" })
    require("luasnip").filetype_extend("javascript", { "jsdoc" })
    require("luasnip").filetype_extend("lua", { "luadoc" })
    require("luasnip").filetype_extend("python", { "pydoc" })
    require("luasnip").filetype_extend("rust", { "rustdoc" })
    require("luasnip").filetype_extend("cs", { "csharpdoc" })
    require("luasnip").filetype_extend("java", { "javadoc" })
    require("luasnip").filetype_extend("c", { "cdoc" })
    require("luasnip").filetype_extend("cpp", { "cppdoc" })
    require("luasnip").filetype_extend("php", { "phpdoc" })
    require("luasnip").filetype_extend("kotlin", { "kdoc" })
    require("luasnip").filetype_extend("ruby", { "rdoc" })
    require("luasnip").filetype_extend("sh", { "shelldoc" })
  end,
},
```

This is my working config using lazy.nvim. I don't see anything else that might be the cause.

**Comment by huyhoang8398** [comment]
Thanks, it is working well now
the configuration is 
`require("luasnip").filetype_extend("python", { "pydoc" })`
instead of `python-docstring` as in your previous example

**Comment by Zeioth** [comment]
You are absolutely right. It seems somehow I fixed it locally but forgot to to push the change to the repo. It's been updated now. Thank you so much for writing back @huyhoang8398
