### ISSUE TITLE
How to jump from placeholder?

### ISSUE THREAD

**Issue by winston0410** [rafamadriz/friendly-snippets#36]
I recently found that that there are placeholders in the snippet declaration. Taking snippet for `func` in `golang` for an example, after completing this snippet, the cursor will end up in `$1` in insert mode.

```json
{
  "function declaration": {
    "prefix": "func",
    "body": "func $1($2) $3 {\n\t$0\n}",
    "description": "Snippet for function declaration"
  }
}

My question is, after completing `$1`, how can I jump to `$2`? Is there any command that I can look for, or is it the responsibility of the snippet engine like `nvim-compe`?

**Comment by rafamadriz** [comment]
It's going to depend on which snippet plugin you use. 

For vsnip here are the example mappings you can use to jump https://github.com/hrsh7th/vim-vsnip#2-setting

For luasnip here are the examples https://github.com/L3MON4D3/LuaSnip#setup

**Comment by winston0410** [comment]
I see. Thank you so much.
