### ISSUE TITLE
Need help to load 2 snippets for one language

### ISSUE THREAD

**Issue by SidonTheTroll** [rafamadriz/friendly-snippets#373]
Hi, I've been customizing my forked repo for writing equations in Markdown. I've been using the autofill function in VS Code, but it's slow. Additionally, I'm accustomed to Vim keybindings. I'd like to know how to add two paths in the package.json file for a single language. This would allow me to include GitHub-supported LaTeX functions from another file, which can be loaded alongside the Markdown snippets.

**Comment by rafamadriz** [comment]
Doing the same from this section of the README should work https://github.com/rafamadriz/friendly-snippets#add-snippets-from-a-framework-to-a-filetype

**Comment by haru02w** [comment]
> Doing the same from this section of the README should work https://github.com/rafamadriz/friendly-snippets#add-snippets-from-a-framework-to-a-filetype

I might be too dumb but I couldn't manage to make it work. Could you provide a code snippet for this? thanks

**Comment by SidonTheTroll** [comment]
> > Doing the same from this section of the README should work https://github.com/rafamadriz/friendly-snippets#add-snippets-from-a-framework-to-a-filetype
> 
> I might be too dumb but I couldn't manage to make it work. Could you provide a code snippet for this? thanks

<img align=right width=450 src="https://github.com/rafamadriz/friendly-snippets/assets/70560640/1dc287d9-b45a-413e-a6e5-93f6441477a7">

Hey update here, I got a way around to do it but it doesn't quite fulfil my expectations. 

The image on the right shows a screenshot from my forked repo. As you can see, it uses multiple instances to check if a file is markdown or not which is inefficient if you want to make adjustments to the filetype as a whole. 

To go in brief, all the markdown snippets are stored in `./snippets/markdown/` directory (work on halt due to my exams) and later modifications are to be expected. Haven't been thinking of pushing these commits to the main directory because not everyone is like me who uses github to store the school notes.

**Comment by SidonTheTroll** [comment]
Note that I haven't been checking the repo at all and I almost forgot how the framework works.
