### ISSUE TITLE
[Feat request] Move Lorem Ipsum snippets out from global

### ISSUE THREAD

**Issue by RenjiSann** [rafamadriz/friendly-snippets#375]
Hi !

I know this is looks like Déjà-vu ( #255  ), but I keep inserting unwanted Lorem Ipsum paragraphs everywhere, which is not very practical.

Wouldn't it be better to move the loremIpsum snippets to their own files ?

**Comment by surmish** [comment]
Seconding this request. Text files are created all the times in people's workflow, the lorem ipsum placeholder text however, is rarely used by anyone.

**Comment by Anthirian** [comment]
Perhaps an alternative is to allow exclusion of the entire `global.json`, for example like this

```lua
require('luasnip').config.setup({
  exclude = { 'global' },
})
```

**Comment by createchange** [comment]
Adding my voice to this. At the very least, expand the trigger word to be `lorem` - I think that is a fine compromise.

**Comment by rafamadriz** [comment]
this seems reasonable, I'm gonna put lorem ipsum snippets into its own file and don't add it into package.json. If someone wants those, they will have to manually load those snippets.

**Comment by OkelleyDevelopment** [comment]
Can we close this issue or is there still a PR/ updates to the documentation we'd like to see?

**Comment by OkelleyDevelopment** [comment]
Closing as the issue has been inactive. If further discussion is needed please re-open :+1:
