### ISSUE TITLE
useState capitalize bug

### ISSUE THREAD

**Issue by sajadspeed** [rafamadriz/friendly-snippets#379]
`useState` does not capitalize the first letter in the second parameter:

![useStatebug](https://github.com/rafamadriz/friendly-snippets/assets/43334402/90e64f3d-1fe4-4b80-b58b-28e97bcaac5c)

**Comment by jtaavola** [comment]
Check this out [LuaSnip#transformations](https://github.com/L3MON4D3/LuaSnip/blob/master/DOC.md#transformations) and https://github.com/L3MON4D3/LuaSnip/issues/651#issuecomment-1336391126

**Comment by OkelleyDevelopment** [comment]
Closing as a suggestion was provided. Feel free to re-open should more input be needed! :sunglasses:
