### ISSUE TITLE
How to contribute to the wiki?

### ISSUE THREAD

**Issue by 0neMiss** [rafamadriz/friendly-snippets#382]
I made some docs for the wiki but I cant push them, so I guess I'll just drop it here unless I can be given access to push changes. Cheers.

#### `createt` Create Regular Table

```sql
CREATE TABLE tableName (
  attribute(s)
);
```

#### `createi` Create Table with Conditional

```sql
CREATE TABLE IF NOT EXISTS tableName (
  attribute(s)
);
```

#### `created` Create Regular Database

```sql
CREATE DATABASE name;
```

#### `createdi` Create Database with Conditional

```sql
CREATE DATABASE IF NOT EXISTS;
```

#### `insert` Insert value(s)

```sql
INSERT INTO tableName (
  attribute(s)
) VALUES ( values )
```

#### `dropt` Drop table

```sql
DROP TABLE tableName;
```

#### `dropd` Drop Database

```sql
DROP DATABASE dbName;
```

#### `dropti` Drop Table with Conditional

```sql
DROP TABLE IF EXISTS tableName;
```

#### `dropdi` Drop Database with Conditional

```sql
DROP DATABASE IF EXISTS tableName;
```

#### `showt` Show Tables

```sql
SHOW TABLES;
```

#### `showd` Show Databases

```sql
SHOW DATABASES;
```

#### `select` Regular Select

```sql
SELECT attribute(s) FROM tableName;
```

#### `selectd` Select Distinct

```sql
SELECT DISTINCT attribute(s)
  FROM tableName;
```

#### `selectw` Select with Condition

```sql
SELECT attribute(s)
  FROM tableName
  WHERE condition;
```

#### `selector` Select with order

```sql
SELECT attribute(s)
  FROM tableName
  ORDER BY attribute(s) ASC|DESC;
```

#### `updatet` Update table

```sql
UPDATE tableName
  SET attribute(s)
  WHERE condition;
```

#### `delete` Delete records

```sql
DELETE FROM tableName
  WHERE condition;
```

#### `altert` Alter table

```sql
ALTER TABLE tableName
   intructions;
```

#### `alterad` Alter table - Add column

```sql
ALTER TABLE tableName
  ADD COLUMN col_name;
```

#### `alteraf` Alter table - Add column after

```sql

ALTER TABLE tableName
  ADD COLUMN col_name
  AFTER col_name;
```

#### `alterdb` Alter database

```sql

ALTER DATABASE dbName
  CHARACTER SET charset
  COLLATE utf8_unicode_ci;
```

#### `ijoin` Inner Join

```sql

SELECT attribute(s)
  FROM tableName
  INNER JOIN tableName2
  ON match;
```

#### `rjoin` Right Join

```sql

SELECT attribute(s)
  FROM tableName
  RIGHT JOIN tableName2
  ON match;
```

#### `ljoin` Left Join

```sql

SELECT attribute(s)
  FROM tableName
  LEFT JOIN tableName2
  ON match;
```

#### `fjoin` Full Join

```sql

SELECT attribute(s)
  FROM tableName
  FULL JOIN OUTER tableName2
  ON match
  WHERE condition;
```

#### `union` Regular Union

```sql

SELECT attribute(s) FROM tableName
UNION
SELECT attribute(s) FROM tableName2;
```

#### `uniona` All union

```sql

SELECT attribute(s) FROM tableName
UNION ALL
SELECT attribute(s) FROM tableName2;
```

#### `groupb` Group by

```sql

SELECT attribute(s)
  FROM tableName
  GROUP BY attribute(s);
```

#### `bakupd` Backup database

```sql

BACKUP DATABASE dbName
  TO DISK filepath;
```

#### `bakupdw` Differential backup database

```sql
BACKUP DATABASE dbName
  TO DISK filepath
  WITH DIFERENTIAL;
```

#### `primaryk` Primary Key

```sql
PRIMARY KEY(attribute)
```

#### `primarykc` Constraint Primary Key

```sql
CONSTRAINT attribute PRIMARY KEY(attribute(s))
```

#### `foreingk` Foreign Key

```sql
FOREIGN KEY(attribute) REFERENCES tableName(attribute)
```

#### `foreingkc` Constraint foreign Key

```sql
CONSTRAINT attribute FOREIGN KEY (attribute(s))
  REFERENCES tableName(attribute)
```

#### `check` Check

```sql
CHECK ( condition )
```

#### `createuser` Create User

```sql
CREATE USER 'username'@'localhost' IDENTIFIED BY 'password';
```

#### `deleteuser` Delete User

```sql
DELETE FROM mysql.user WHERE user = 'userName';
```

#### `grantuser` Grant Privileges

```sql
GRANT ALL PRIVILEGES ON db.tb TO 'user_name'@'localhost';
```

**Comment by OkelleyDevelopment** [comment]
Appreciate the help @0neMiss ! While I can make the updates to the wiki, I think @rafamadriz would need to grant access per individual (to ensure random edits aren't being made). 

Though if this understanding is wrong, feel free to correct me (it has been some time since I last configured a repository wiki :sweat_smile: )

**Comment by 0neMiss** [comment]
No worries! I don't mind if the updates are made for me, unless you would like more help with doing wiki updates which I would gladly participate in! Thanks

**Comment by OkelleyDevelopment** [comment]
My apologies on the delay @0neMiss, but the page has been created [here](https://github.com/rafamadriz/friendly-snippets/wiki/SQL)! 

I modified the initial "note" message on format, but otherwise it's basically just a copy-paste to the page. 

Let me know if you'd like anything modified or if it's good to go for now :sunglasses:
