### ISSUE TITLE
Terraform snippets are missing on package.json

### ISSUE THREAD

**Issue by JeSappelleRoot** [rafamadriz/friendly-snippets#385]
Hi there, 

I'm using classic setup on my neovim, with Lazy as plugin manager, nvim-cmp as autocomplete, LuaSnip as snippets engine. 

Here a quick extract of my lsp.lua that I initiate from my init.lua with a simple `require('lsp')`
> still a newbie on Neovim (started 1 week ago, don't judge my config :stuck_out_tongue:)

```lua

-- Forcing Terraform filetype here
vim.cmd([[silent! autocmd! filetypedetect BufRead,BufNewFile *.tf]])
vim.cmd([[autocmd BufRead,BufNewFile *.hcl set filetype=hcl]])
vim.cmd([[autocmd BufRead,BufNewFile .terraformrc,terraform.rc set filetype=hcl]])
vim.cmd([[autocmd BufRead,BufNewFile *.tf,*.tfvars set filetype=terraform]])
vim.cmd([[autocmd BufRead,BufNewFile *.tfstate,*.tfstate.backup set filetype=json]])

vim.cmd([[let g:terraform_fmt_on_save=1]])
vim.cmd([[let g:terraform_align=1]])

-- Forcing filetype on Docker Compose
vim.cmd([[autocmd BufRead,BufNewFile docker-compose.yml set filetype=yaml.docker-compose]])

local capabilities = require("cmp_nvim_lsp").default_capabilities()
require("mason").setup()
require("mason-lspconfig").setup {
    ensure_installed = { "terraformls", "tflint", "dockerls", "docker_compose_language_service", "pyright" },
}
local lspconfig = require('lspconfig')


-- Enable some language servers with the additional completion capabilities offered by nvim-cmp
local servers = { "terraformls", "tflint", "dockerls", "docker_compose_language_service", "pyright" }
for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    -- on_attach = my_custom_on_attach,
    capabilities = capabilities,
  }
end

-- luasnip setup
local luasnip = require 'luasnip'
require('luasnip.loaders.from_vscode').lazy_load()
[...]
```

Snippets on markdown or even Python are working fine, however Terraform snippets seems empty

* Python

![image](https://github.com/rafamadriz/friendly-snippets/assets/52102633/b4a0ee26-f3b8-4ff6-8ce4-a2871b566e1e)
![image](https://github.com/rafamadriz/friendly-snippets/assets/52102633/c2675902-c02a-4174-87d8-14a8191e8295)

* Markdown

![image](https://github.com/rafamadriz/friendly-snippets/assets/52102633/9d84f96e-3cb8-4e56-b4e8-c7dc77852bb4)
![image](https://github.com/rafamadriz/friendly-snippets/assets/52102633/f75546c1-f751-41c5-9826-4050b8ba3104)

**However, Terraform snippets seems empty**
![image](https://github.com/rafamadriz/friendly-snippets/assets/52102633/2ad5194b-b55c-464d-a7d4-76af5ca395f4)

After checking on `~/.local/share/nvim/lazy/friendly-snippets` files and checking logs with `:lua require('luasnip').log.open()` command I found that Terraform snippets declaration could be missing from package.json

Here the fix : 
![image](https://github.com/rafamadriz/friendly-snippets/assets/52102633/e515939e-5fc5-4bb6-8357-9dbad80c2c98)

![image](https://github.com/rafamadriz/friendly-snippets/assets/52102633/ec663b78-c22e-49ed-8ad0-3e1b16c8e7b7)
![image](https://github.com/rafamadriz/friendly-snippets/assets/52102633/c4570737-20ef-4487-8c12-b2e19f03cbf5)

I can raise a PR with the fix, let me know :pray: 
Best, 

JeSappelleRoot

**Comment by donaldgifford** [comment]
Same issue as above. Manually set it works fine.

**Comment by JeSappelleRoot** [comment]
Any update on this issue ? We could raise a PR to add necessary fix
Let us know

Best, 
JeSappelleRoot

**Comment by stepan111** [comment]
Got same issue

**Comment by armyers** [comment]
thank you! :)
