### ISSUE TITLE
LaTeX/TeX snippets

### ISSUE THREAD

**Issue by krisfans** [rafamadriz/friendly-snippets#4]
Hello and thank you for the snippets!

Is it possible to add to your list snippets for LaTeX? I found these:

https://github.com/James-Yu/LaTeX-Workshop/blob/master/snippets/latex.json

This is a widely-used LaTeX plugin for VS Code .

**Comment by rafamadriz** [comment]
Thanks for the suggestion, they were added. 

![2021-Apr- 2](https://user-images.githubusercontent.com/67771985/113420140-4ec91a80-93b8-11eb-9adc-fa772f35478e.png)
![2021-Apr- 2_1](https://user-images.githubusercontent.com/67771985/113420143-4ffa4780-93b8-11eb-989a-4343cdced64d.png)

**Comment by argapost** [comment]
They dont work for me. Previously I had manually put them in .vsnip/tex.json and they worked, I removed them now and updated your plugin but they don't work.
