### ISSUE TITLE
which filetype for 'plantuml' snippets

### ISSUE THREAD

**Issue by gitacrobat** [rafamadriz/friendly-snippets#400]
I see that 'plantuml' snippets are supported. But they don't show up for me.

The plugin works with GdScript files. So maybe I am using a wrong file type?

**Comment by OkelleyDevelopment** [comment]
Hi @gitacrobat, I checked again and it seems you will need to add a line to you configuration to set the file type. 

E.g. `init.lua`, below will support `*.plantuml` and `*.puml`.

```lua
vim.cmd('autocmd BufNewFile,BufRead *.plantuml set filetype=plantuml')
vim.cmd('autocmd BufNewFile,BufRead *.puml set filetype=plantuml')
```

**Comment by OkelleyDevelopment** [comment]
Closing, feel free to re-open if you run into further issues :sunglasses:
