### ISSUE TITLE
Vue snippets trigger when inside curly braces

### ISSUE THREAD

**Issue by 0x1DA117** [rafamadriz/friendly-snippets#406]
I'm not sure if this is an issue with friendly-snippets or not, but to me it seems so.
I'm using `nvim-cmp` with `LuaSnip` and this opens the autocompletion popup when the cursor is inside curly braces.

To me this usually happen when I type `function() {}` and jump back between the curly braces, but it also when I just type `{}` without the `function()` part.

To check where this is coming from, I excluded the `vue` and the `global` snippets (global snippets also appear in the list).

This behavior is a bit annoying because I usually just hit enter when the cursor is between the curly braces, which completes the first item and messes up my function.

If this behavior doesn't belong to friendly-snippets, please let me know.

<img width="610" alt="Screenshot 2024-02-19 at 20 53 38" src="https://github.com/rafamadriz/friendly-snippets/assets/4022138/47183f97-ffb5-4cfa-a029-5415b19c5f3e">

**Comment by 0x1DA117** [comment]
Well, I don't know. This is my cmp config.

```lua
    cmp.setup({
      snippet = {
        expand = function(args)
          luasnip.lsp_expand(args.body)
        end,
      },
      completion = {
        completeopt = 'menu,menuone,noinsert',
      },
      mapping = cmp.mapping.preset.insert {
        ['<C-n>'] = cmp.mapping.select_next_item(),
        ['<C-p>'] = cmp.mapping.select_prev_item(),
        ['<C-b>'] = cmp.mapping.scroll_docs(-4),
        ['<C-f>'] = cmp.mapping.scroll_docs(4),
        ['<C-Space>'] = cmp.mapping.complete({}),
        ['<CR>'] = cmp.mapping.confirm({
          behavior = cmp.ConfirmBehavior.Replace,
          select = true,
        }),
        ['<Tab>'] = cmp.mapping(function(fallback)
          if cmp.visible() then
            cmp.select_next_item()
          elseif luasnip.expand_or_locally_jumpable() then
            luasnip.expand_or_jump()
          else
            fallback()
          end
        end, { 'i', 's' }),
        ['<S-Tab>'] = cmp.mapping(function(fallback)
          if cmp.visible() then
            cmp.select_prev_item()
          elseif luasnip.locally_jumpable(-1) then
            luasnip.jump(-1)
          else
            fallback()
          end
        end, { 'i', 's' }),
      },
      sources = {
        { name = 'nvim_lsp' },
        { name = 'luasnip' },
        { name = 'path' },
      },
    })
```

**Comment by bobbyrahmanda13** [comment]
I share my config
![image](https://github.com/rafamadriz/friendly-snippets/assets/69358107/974ab5d4-df22-4893-8d43-df416178551d)
![image](https://github.com/rafamadriz/friendly-snippets/assets/69358107/04360f24-9bd2-4bc3-88e8-a7421a69ba1f)

![image](https://github.com/rafamadriz/friendly-snippets/assets/69358107/fdf1eb34-6e14-4079-a9cc-aa8e791ecbf5)

**Comment by bobbyrahmanda13** [comment]
See for yourself I haven't added that snippet but I want to make it, maybe there's an error in your config, because for me it's not a problem

**Comment by bobbyrahmanda13** [comment]
I will move all the javascript and typescript snippets into script.json so I no longer need file_extend javascript or typescript, because vue is html css and javascript or typescript, therefore I made style.json which will contain vanilla CSS and tailwind CSS or unocss, That's my plan, hopefully I have time to do it

**Comment by OkelleyDevelopment** [comment]
@0x1DA117 on first pass, this looks like an issue with your `LuaSnip` setup. However, I'm unsure at the moment where things are going wrong :thinking:

**Comment by bobbyrahmanda13** [comment]
The problem has been solved, can it be closed?
