### ISSUE TITLE
Please include Blade snippets.

### ISSUE THREAD

**Issue by dharmx** [rafamadriz/friendly-snippets#413]
Hello!

Thank you for your work.
If it is not much trouble, It would be really nice if you could include snippets from [laravel-blade-snippets-vscode](https://github.com/onecentlin/laravel-blade-snippets-vscode) repository.

Sincerely,
dharmx

**Comment by t0mri** [comment]
already did with #374

**Comment by dharmx** [comment]
Thank you.
