### ISSUE TITLE
Remove trivial snippets

### ISSUE THREAD

**Issue by dev-ardi** [rafamadriz/friendly-snippets#416]
There are many snippets that don't do much, such as 
```json
    "mod": {
        "prefix": "mod",
        "body": ["mod ${1:name};"],
        "description": "mod …;"
```
Having the snippet is not very useful in this case. Snippets should be reserved for common idioms that are somewhat annoying/long to type.

These should be removed to reduce noise and to allow more snippets in the future.

There are also some extremely niche macros that here such as `include!()`, `column!()` and `line()!` which I'm not sure why they are even snippets

**Comment by OkelleyDevelopment** [comment]
Hi @dev-ardi, I started a PR [here](https://github.com/rafamadriz/friendly-snippets/pull/428), to address this issue. When you get a moment, I'd appreciate your thoughts on the snippets removed.
