### ISSUE TITLE
Add snippets for Gleam

### ISSUE THREAD

**Issue by tobsz** [rafamadriz/friendly-snippets#418]
It would be great, if snippets for the Gleam programming language would be added. A [ready JSON](https://raw.githubusercontent.com/gleam-lang/vscode-gleam/main/snippets.json) already exists.

Should I just make a PR for it?

**Comment by OkelleyDevelopment** [comment]
Hi @tobsz 👋 opening a PR is good as it'll let others see it ahead of time. Just make sure to reference this issue in the PR title or description.
