### ISSUE TITLE
Can't see unity snippets

### ISSUE THREAD

**Issue by MyGitHubBlueberry** [rafamadriz/friendly-snippets#425]
Hello. I'm pretty sure this is skill issue, which I didn't managed to solve so far, but I have a problem accessing unity snippets.
I'm using following line of code to import snippets, but unfortunately  I can't see them:
 `require('luasnip').filetype_extend("csharp", { "unity" })` 
 
 luasnip and friendly-snippets are imported and installed.
 Any help is appreciated. 👍

**Comment by OkelleyDevelopment** [comment]
Hi @MyGitHubBlueberry, I too was stumped :sweat_smile: but realized our error. Vim recognizes C# files as `cs` so try this:
```lua
require("luasnip").filetype_extend("cs", { "unity" })
```

**Comment by MyGitHubBlueberry** [comment]
@OkelleyDevelopment Thank you, it works now :)
I'm quite confused because I tried "cs" before and it didn't worked for some reason (maybe i forgot to "so" my config), but it works now. Appreciate your help. 🤞
