### ISSUE TITLE
Example of selectively applying snippets

### ISSUE THREAD

**Issue by danieleavitabile** [rafamadriz/friendly-snippets#431]
I use LuaSnip, and have developed a number of LaTeX snippets. I am now considering adopting friendly-snippets for other languages, while keeping exclusively my own LaTeX snippets for .tex files.

Is there a clear set of instructions for doing that? It's unclear to me whether the instructions for disabling snippets in the home page will disable all tex snippets (including mine) or will only disable the friendly-snippet latex snippets.

**Comment by AidenAllredOfficial** [comment]
Hi! You should be able do this by adding the following to your NeoVim config.
`
require("luasnip.loaders.from_vscode").load {
    exclude = { "tex", "plaintex" },
}
`

**Comment by OkelleyDevelopment** [comment]
I believe the above snippet should accomplish your goal. 

Generally the way to handle this will differ between snippet engines, so I will always say to refer back to their docs as this repo just supplies the snippets for the engine to load. 
:slightly_smiling_face: 

I will close this issue, but feel free to re-open should any other questions/concerns arise!

**Comment by OkelleyDevelopment** [comment]
Hi @danieleavitabile , I was successful in preventing the snippets from loading by using the `exclude` field in the loader:

```lua
local vscode_loader = require("luasnip/loaders/from_vscode")
vscode_loader.lazy_load({
    exclude = { "latex", "tex" }
})
```

However, due to how LuaSnip currently parses the files ([here](https://github.com/L3MON4D3/LuaSnip/blob/878ace11983444d865a72e1759dbcc331d1ace4c/lua/luasnip/loaders/types.lua#L4-L5)), it seems your request is not possible.


Alternatively, we CAN do modify the priority of your snippets. See [here](https://github.com/rafamadriz/friendly-snippets/issues/431) for a recent explanation.

**Comment by OkelleyDevelopment** [comment]
Hi again @danieleavitabile, 

I was wrong! We CAN exclude the files like you asked (it just helps for me to INCLUDE my own LaTeX snippets in the snippets directory correctly :man_facepalming: ).

```lua
local vscode_loader = require("luasnip/loaders/from_vscode")
vscode_loader.lazy_load({
    exclude = { "latex", "tex" }
})

vscode_loader.load({ paths = "/home/<$USER>/.config/nvim/snippets/"})
```

Let me know if this helps, then we can make an edit to the docs to provide an example with Luasnip!

**Comment by OkelleyDevelopment** [comment]
Any updates @danieleavitabile? Did this work for you too?

**Comment by danieleavitabile** [comment]
I had no chance to try yet, sorry.


On 17 June 2024 at 05:41:31, OkelleyDevelopment ***@***.******@***.***>) wrote:

Any updates @danieleavitabile<https://github.com/danieleavitabile>? Did this work for you too?

**Comment by OkelleyDevelopment** [comment]
Closing issue as I believe we've provided a working solution now. If further issues do arise, feel free to re-open this issue :+1:
