### ISSUE TITLE
Excluding specific snippets from specific filetype

### ISSUE THREAD

**Issue by fmorroni** [rafamadriz/friendly-snippets#439]
Hi, I see there's a way to exclude all snippets of a specific language, but I'd like to exclude specific snippets. For example I have a custom `for` snippet for javascript and I would like to disable the friendly-snippets' one, while still leaving the rest active. 
Is this currently possible?

**Comment by OkelleyDevelopment** [comment]
Hi @fmorroni, I don't currently have a lua snippet to share. However, I can recommend this alternative (assuming you're using LuaSnip as the snippet engine):

```json
{
  "custom-for-loop": {
    "prefix": "for",
    "body": "for { $0 }",
    "luasnip": {
      "priority": 2000
    }
  }
}
```

where the important part is this:
```json
"luasnip": {
  "priority": 2000
}
```

This will place the custom for loop snippet above the one loaded from `friendly-snippets`. Pretty sure the number just needs to be >= 100, but test around and see for yourself. I tested with 2000 and it worked ... so let me know if this helps (at least in the short term)! :slightly_smiling_face:

**Comment by OkelleyDevelopment** [comment]
Going to close this issue as any further work would be dependent on the snippet engines capabilities.
