### ISSUE TITLE
Is snippet inheritance an upstream issue?

### ISSUE THREAD

**Issue by winston0410** [rafamadriz/friendly-snippets#45]
Is it possible to achieve snippet inheritance with friendly-snippet, or is that an upstream issue? Let say I have a snippet that will generate the following in Kotlin:

```json
{
  "variable declaration": {
    "prefix": "var",
    "body": "var ${1:name} = ${2:value}",
    "description": "Snippet for a variable"
  }
}
```
Generating this:
```kotlin
var name = value
```

Now I want to add the keyword `override` into the mix, and generate this:

```kotlin
override var name = value
```

Is it possible to make a snippet that extends the original snippet and add `override` in front of it? Where can I find the doc and its related syntax?

**Comment by rafamadriz** [comment]
It may also depend on which snippet plugin you use.

**Comment by winston0410** [comment]
@rafamadriz thanks. I have been copy and pasting without knowing the source of the convention. Thank you.

The plugin I am using is `nvim-compe` and `vim-vsnip`, does that ring a bell?

**Comment by rafamadriz** [comment]
From the vim-vsnip README: 

> - Nested snippet expansion
        -You can expand snippet even if you already activated other snippet (it will be merged as one snippet)

Is that what you're looking for ?

**Comment by winston0410** [comment]
@rafamadriz yes thats right and I think that is something I need. thanks
