### ISSUE TITLE
Escaping in LaTeX snippets involving math

### ISSUE THREAD

**Issue by pitkling** [rafamadriz/friendly-snippets#459]
The vscode LaTeX snippets that involve math (or at least some of them) do not properly escape the math delimiter `$`. See for example the [Inline Math](https://github.com/rafamadriz/friendly-snippets/blob/d0610077b6129cf9f7f78afbe3a1425d60f6e2f1/snippets/latex/vscode-latex-snippets.json#L82-L86) snippet. It's body is `$ $1 $$0`, but from the [vscode grammar definition](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_grammar) I would have expected the body should be `\\$ $1 \\$$0` (double escape necessary because of the JSON file format).

Is this intended? It seems some snippet engines can cope without the escaping (e.g., [LuaSnip](https://github.com/L3MON4D3/LuaSnip) plugin for Neovim), while others (like the integrated snippet expansion in Neovim 10+ via `vim.snippet.expand`) choke on the unescaped snippets.

**Comment by DimitrisDimitropoulos** [comment]
I think you are correct. I tested your suggestion and it seems to work as expected, at least with luasnip. I think that the escaping fixes the issue with native snippets. I created a PR #473

**Comment by OkelleyDevelopment** [comment]
That PR has been merged, perhaps @pitkling can confirm as well?

**Comment by pitkling** [comment]
Great, thanks @DimitrisDimitropoulos! The updated snippets work now fine with the native snippet expansion :).

I spotted a few more that need a similar update: Pretty much every snippet in `vscode-latex-snippets.json` that has a line containing `addlegendentry` does not properly escape the math inside the `addlegendentry` macro. The only snippets that does the escaping correctly at the moment is `plotgraph3d`.

**Comment by OkelleyDevelopment** [comment]
Just approved and merged #476. If @pitkling can confirm, then I think this issue can be (finally) closed :partying_face:

**Comment by pitkling** [comment]
Everything seems fine now, thanks! :)
