### ISSUE TITLE
How to setup friendly snippets with native nvim snippet ?

### ISSUE THREAD

**Issue by cr4ftx** [rafamadriz/friendly-snippets#484]
Everything is in the title 👌

**Comment by sulrich** [comment]
fwiw - i've found the following plugin to do the trick nicely. 

https://github.com/garymjr/nvim-snippets

**Comment by OkelleyDevelopment** [comment]
I've closed this issue since that plugin linked above looks like a nice solution. If there are more specifics to this question (e.g. error messages, etc), feel free to re-open.

**Comment by cr4ftx** [comment]
FYI I've just switched to https://github.com/saghen/blink.cmp which has a native support for friendly-snippet
