### ISSUE TITLE
about change snippets

### ISSUE THREAD

**Issue by neuromagus** [rafamadriz/friendly-snippets#488]
I want to change snippets for react. Now not needed "import React blah-blah". But maybe people uses old version of this lib. So, I want ask somebody, "friendly-snippets" have mechanisme for enable/disable something? For creating construction with option "Enable React import" or "replace div to fragment <>" and (i try to pull request in react snippets for vscode, but repo is dead...) set in snippet construction for choice (if/else)?

P.S. sorry for my eng.

**Comment by OkelleyDevelopment** [comment]
Hi @neuromagus, `friendly-snippets` doesn't have a "mechanism" per-se to choose between two sets of snippets. We simply provide the snippets and then rely on the consumer to specify what they want to load.

The `package.json` in this repo provides some defaults and for other frameworks/languages simply specifies the path to the snippets which end users can then load either
- by extending an existing set of snippets (e.g. react extending JS snippets)
- their editor specifying a filetype should load the framework/language. 

Let me know if that answers your question or if there are any clarifications needed. :slightly_smiling_face:

**Comment by neuromagus** [comment]
thanks for your answer, @OkelleyDevelopment.
