### ISSUE TITLE
LaTeX snippets not working

### ISSUE THREAD

**Issue by argapost** [rafamadriz/friendly-snippets#5]
In order to make the latex snippets to work I had to change in the package.json file

"language": ["plainlatex", "tex"],

**Comment by rafamadriz** [comment]
Thanks for reporting, that's weird they worked for me with just `"language": "plaintext"`. But I added your fix,.

**Comment by argapost** [comment]
Ok they work now! It is strange indeed I don't know why. Thank you anyway.
