### ISSUE TITLE
Angular snippets

### ISSUE THREAD

**Issue by blyedev** [rafamadriz/friendly-snippets#502]
Would you be open to a pr dividing the angular snippets by filetype to reduce displayed snippets in each filetype? (obv i would preserve the original filetype for backwards compatibility)

I'm also debating if I could refresh the snippet list as the angular ecosystem evolved significantly since the snippets were written but I cannot promise anything due to tight deadlines.

**Comment by OkelleyDevelopment** [comment]
Feel free to open a PR, others have been known to give early feedback too so this could help.

**Comment by OkelleyDevelopment** [comment]
I'll close this issue since it was just a question, but feel free to re-open if you have more comments.
