### ISSUE TITLE
html snippets don't work with vsnip and nvim compe

### ISSUE THREAD

**Issue by joseSource** [rafamadriz/friendly-snippets#51]
Nvim -v = v.06.dev
- with vim plug
here is the link for my nvim config files

[https://github.com/joseSource/dotfiles/tree/master/nvim](url)

**Comment by rafamadriz** [comment]
Please provide a minimal config to reproduce, it works for me. 

Also consider that this is just a snippet collection in json files. There isn't any code that neovim us loading from this. So most likely the problem won't have anything to do with this "plugin"

**Comment by ndav1d** [comment]
not working for me either (and I'm using packer.nvim)
CSS and other ones work fine

**Comment by ten3roberts** [comment]
I am having the same issue after switching to nvim-cmp

**Comment by ndav1d** [comment]
just switched now and nothing changed, I experience the same issue on both `nvim-compe` and `nvim-cmp`

**Comment by ndav1d** [comment]
actually I just checked that CSS snippets aren't working as well. I think no snippets are...

**Comment by OkelleyDevelopment** [comment]
Since it seems this was resolved, I am closing this issue. If something comes up feel free to reopen / open a new issue :smile:
