### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AnkushRoy-code** [rafamadriz/friendly-snippets#510]
Not a bug/issue just a question.

There are useful snippets for cpp and other languages that are inside a different file called cppdoc.json (cdoc.json, csharpdoc.json, luadoc.json, rustdoc.json and many more),  when are they activated or do I have to enable them somehow? I mean I don't see or can use these snippets in my normal files.

**Comment by barraIhsan** [comment]
You can add snippet from other filetype to your filetype
See https://github.com/rafamadriz/friendly-snippets/blob/main/README.md#add-snippets-from-a-framework-to-a-filetype

Honestly, I'm confused why not all the javascript snippet are inside typescript snippet by default, and if you include it, there is duplicate such as `settimout` snippet
![image](https://github.com/user-attachments/assets/2c5a9879-c495-4f59-93ca-14c41b35edfc)
![image](https://github.com/user-attachments/assets/fa6c4245-0869-4452-a424-1d90c65f73f9)

**Comment by AnkushRoy-code** [comment]
Ooh.., that'll be really helpful thank you very much!
