### ISSUE TITLE
php snippets broken because $$ doesn't properly escape $ under neovim vsnip

### ISSUE THREAD

**Issue by shxfee** [rafamadriz/friendly-snippets#6]
I have to change snippets that contain `$$` to `\\$` for it to work. Otherwise vsnip errors out and just prints the snippet up to the point $$ was used. The rest is truncated.

So given the following snippet

```
	"foreach …": {
		"prefix": "foreach",
		"body": [
			"foreach ($${1:variable} as $${2:key} ${3:=> $${4:value}}) {",
			"\t${0:# code...}",
			"}"
		],
		"description": "Foreach loop"
	}
```

only the following is printed

`    foreach (`

However when $ is escaped properly using \\$ it works as expected.

**Comment by rafamadriz** [comment]
Hey, I fixed the issue. Let my know if they work for you.

**Comment by shxfee** [comment]
awesome!
