### ISSUE TITLE
Global snippets not recognized

### ISSUE THREAD

**Issue by ranebrown** [rafamadriz/friendly-snippets#8]
The `diso` snippet in the global snippet file doesn't show up for me. If I copy that file to my `g:vsnip_snippet_dir` it works as expected. Maybe related to the package.json file?

**Comment by rafamadriz** [comment]
I haven't got global snippets to work either, I need to find a way to make it apply to all filetypes. The best I can think of is to make a list of all the filetypes in the language section of the package.json. But that's a very... hacky solution to say the least, and it would be a huge array of filetypes just for those snippets. I'm gonna test today again and try to find a solution.
