### ISSUE TITLE
Python: parenthesis trigger same 3 snippets

### ISSUE THREAD

**Issue by argapost** [rafamadriz/friendly-snippets#81]
Hello,

Just a repost of this issue: https://github.com/saadparwaiz1/cmp_luasnip/issues/15

When I open or close parenthesis in python I get the following 3 snippets no matter the function:

![image](https://user-images.githubusercontent.com/58076098/134481336-d1ca7367-0604-4df4-b614-7730c38e50fd.png)

Is it possible to change the prefix of these 3 snippets to not include () so they will not be triggered every time we open or close parenthesis? 

I get the following behaviour with luasnip but the same seems to be happening with vsnip.

Thank you in advance!

**Comment by d-miketa** [comment]
I have the same issue.

@rafamadriz, I think the completion's triggered by a fuzzy match between the opening parenthesis `(` and `def(class method)`.
