### ISSUE TITLE
[Feat request] Avoid assigning multiple snippet sources to a single language

### ISSUE THREAD

**Issue by lambtho12** [rafamadriz/friendly-snippets#88]
In my opinion, it would be better to avoid linking a single language to multiple snippet files. 
For instance, snippets for markdown are loaded from [global.json](https://github.com/rafamadriz/friendly-snippets/blob/main/snippets/global.json), [markdown.json](https://github.com/rafamadriz/friendly-snippets/blob/main/snippets/markdown.json) and [vscode-jekyll-snippets.json](https://github.com/rafamadriz/friendly-snippets/blob/main/snippets/jekyll/vscode-jekyll-snippets.json). In my personal experience, I do not use jekyll. Therefore, the jekyll-specific snippets are just irrelevant; worse, they even conflict with some custom snippets I have set.

I believe ([and so is the developer of luasnip](https://github.com/L3MON4D3/LuaSnip/issues/197#issuecomment-941238032)) that it should be the job of the snippet engine to mix the various files according to the desired filetype/framework and not the job of the source to pre-mix them.

What do you think of it?

**Comment by lambtho12** [comment]
The way I see it, this repository should be considered only as a snippet source dictionary. Therefore it should only provide snippets related to the language itself by default and provide separately framework snippets (rails, jekyll, vue, etc). Then it should be the job of the snippet engine (LuaSnip for instance) to mix them or provide an option to load multiple snippet files for a given filetype.

A fix may be to use a specific field in the package.json to identify framework snippets (and keep the language field in order to specify the related language).
```
{
  "framework": "jekyll",
  "language" : "markdown",
  "path": "./snippets/jekyll/vscode-jekyll-snippets.json"
 },
```

Then snippets engine could only load snippets without the framework field by default and provide an option to also load specific framework ones.

@L3MON4D3 (dev of [LuaSnip](https://github.com/L3MON4D3/LuaSnip)) or maybe @leiserfg, do you have a better idea?

**Comment by rafamadriz** [comment]
Okay I see, thanks for explaining.  

> or make luasnip search markdown and jekyll snippets via some other mechanism

What would other mechanism ? my problem with setting `ft` to `markdown.jekyll` for example, is that messes up wit syntax highlighting, in markdown might not be a big deal since is pretty simple, but what if you want to do the same with javascript, adding react snippets with `javascript.react`. That's why I wonder what is the other way of doing it.  

You mean this mechanism `luasnip.filetype_extend("html", {"jekyll"})` ?

**Comment by L3MON4D3** [comment]
Yeah, that's the one.
Works globally though, so not a complete replacement to changing `ft`

**Comment by rafamadriz** [comment]
>  Works globally though, so not a complete replacement to changing ft

How globally ?

**Comment by rafamadriz** [comment]
Okay thanks for your time, I'll make the necessary changes. I'll also add instructions in README, so people know how to add extra snippets from frameworks. 

Downside is that this will only work wit luasnip, but I think is the best choice, I really don't like having a bunch of irrelevant snippets added by default.

**Comment by L3MON4D3** [comment]
Nice, that's great to hear :D
Looks like `vsnip` also has a comparable mechanism ([doc](https://github.com/hrsh7th/vim-vsnip/blob/master/doc/vsnip.txt#L78-L84)), so vsnip-users are also covered.
