### ISSUE TITLE
friendy-snippets doesn't work on Luasnip.

### ISSUE THREAD

**Issue by arionrefat** [rafamadriz/friendly-snippets#94]
friendy-snippets doesn't work on Luasnip out of the box, do I need to do add any configs?
Here are my, lsp-config , nvim-cmp and lua-snip config
https://github.com/arionrefat/dotfiles/blob/master/neovim/.config/nvim/lua/neovim-lsp-config.lua
https://github.com/arionrefat/dotfiles/blob/master/neovim/.config/nvim/lua/neovim-snip.lua
https://github.com/arionrefat/dotfiles/blob/master/neovim/.config/nvim/lua/compe-config.lua

**Comment by arpangreat** [comment]
You can add this anywhere in config to do so

```lua
require("luasnip/loaders/from_vscode").lazy_load()
```

**Comment by arionrefat** [comment]
It Works now,  thank you. Shouldn't it be included in the README.md?

**Comment by arpangreat** [comment]
> It Works now, thank you. Shouldn't it be included in the README.md? or did I missed it?

It is on LuaSnip Example/snippets.lua
https://github.com/L3MON4D3/LuaSnip/blob/72323c10fe2d91695f7593e572496ab9f004afee/Examples/snippets.lua#L263-L274 here :)

**Comment by arionrefat** [comment]
ow sorry, I should have researched more :(

**Comment by arpangreat** [comment]
@Myzel394 you didn't setup luasnip as I seen in your dots, first setup with cmp as per cmp docs , then the above line will work properly

**Comment by Myzel394** [comment]
@arpangreat oh thanks for taking a look; unfortunately, I didn't commit what I was trying :C

I did follow your advice now, but I'm still not able to get it to run (thought I guess it's my fault and not an issue with the plugins).
So I added `nvim-cmp` (https://github.com/Myzel394/dotfiles/blob/main/nvim/lua/configs/packer.lua#L129):

```lua
    use {
        "L3MON4D3/LuaSnip",
        dependencies = { "rafamadriz/friendly-snippets" },
    }
    use "hrsh7th/nvim-cmp"
    use { "saadparwaiz1/cmp_luasnip" }
```

and I'm initialising cmp right here (https://github.com/Myzel394/dotfiles/blob/main/nvim/after/plugin/cmp.lua#L9):

```lua
snippet = {
        expand = function(args)
            require 'luasnip'.lsp_expand(args.body)
        end
    },
```

however, when I go to a `*.html` file for example, and enter `:LuaSnipListAvailable`, all I see is:

```
{                                                                                                                                                                                                                                    
  all = {},
  html = {}
}
Press ENTER or type command to continue
```

do you know how to fix this? :/

**Comment by arpangreat** [comment]
@Myzel394 in packer the `dependencies` is called `requires` , basically the same thing but different name.

And also packer is unmaintained right now, so move onto lazy.nvim but the above should resolve your problem .

**Comment by Myzel394** [comment]
> @Myzel394 in packer the `dependencies` is called `requires` , basically the same thing but different name.
> 
> And also packer is unmaintained right now, so move onto lazy.nvim but the above should resolve your problem .

Lol that was literally the reason why it didn't work xD Anyway, thank you very much, I'm glad snippets are working now!

> And also packer is unmaintained right now, so move onto lazy.nvim

Thanks for the notice, I'll make sure to migrate soon :D

**Comment by arpangreat** [comment]
No problem mate 🫶, yeah and using it will boost nvim startup time by default.

**Comment by Ali-Aref** [comment]
I know it's solved but its not working me. almost 2 days trying to make it work.
here are my dot files.
https://github.com/Ali-Aref/nv-config

here is my lazy.nvim plugins
```
return {
	{ "VonHeikemen/lsp-zero.nvim", branch = "v3.x" },
	{ "neovim/nvim-lspconfig" },
	{ "hrsh7th/cmp-nvim-lsp" },
	{ "hrsh7th/nvim-cmp" },
	{
		"L3MON4D3/LuaSnip",
		dependencies = { "rafamadriz/friendly-snippets" },
		config = function()
			require("luasnip.loaders.from_vscode").lazy_load()
		end,
	},
}
```
and here is the lsp configs
```
local lsp_zero = require("lsp-zero")

lsp_zero.on_attach(function(client, bufnr)
	lsp_zero.default_keymaps({ buffer = bufnr })
end)

-- for lanugage server check
-- https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md

-- auto complete
local cmp = require("cmp")

cmp.setup({
	snippet = {
		expand = function(args)
			require("luasnip").lsp_expand(args.body)
		end,
	},
	sources = {
		{ name = 'nvim_lsp' },
		{ name = 'luasnip' },
	},
	mapping = {
		["<CR>"] = cmp.mapping.confirm({ select = false }),
		["<C-e>"] = cmp.mapping.abort(),
		["<Tab>"] = cmp.mapping.select_next_item({ behavior = "select" }),
		["<S-Tab>"] = cmp.mapping.select_prev_item({ behavior = "select" }),
	},
	formatting = {
		-- fields = { "menu", "abbr", "kind" },
	},
})
```
it is not detecting friendly snippets. it works only for lsp.
