### ISSUE TITLE
JS snippets dont work on vue files

### ISSUE THREAD

**Issue by siduck** [rafamadriz/friendly-snippets#95]
JS snippets didnt work on vue files but did work on jsx files , is this normal? Also would it be possible to make them work on vue files? :thinking:

**Comment by calvinchoy** [comment]
I was facing the same problem. I think only the snippets inside the frameworks/vue folder are being loaded for vue. If you copy that javascript snippets inside vue/javascript it will be loaded.

**Comment by rafamadriz** [comment]
should work now, let me know.

**Comment by calvinchoy** [comment]
Working fine now, thanks!

**Comment by siduck** [comment]
@rafamadriz sorry to bother! could you include svelte too?

**Comment by shubham-cpp** [comment]
> JS snippets didnt work on vue files but did work on jsx files , is this normal? Also would it be possible to make them work on vue files? thinking

Better solution might be
```lua
vim.g.vsnip_filetypes = {
    vue = { "javascript", "html" },
}
```
